// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/medicine_course_listview_item_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8650434618452904353),
      name: 'MedicineCourseListViewItemModel',
      lastPropertyId: const IdUid(3, 6327909229550554017),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8347654834679933989),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7173028985818334418),
            name: 'topic',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6327909229550554017),
            name: 'medicines',
            type: 30,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8650434618452904353),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    MedicineCourseListViewItemModel: EntityDefinition<
            MedicineCourseListViewItemModel>(
        model: _entities[0],
        toOneRelations: (MedicineCourseListViewItemModel object) => [],
        toManyRelations: (MedicineCourseListViewItemModel object) => {},
        getId: (MedicineCourseListViewItemModel object) => object.id,
        setId: (MedicineCourseListViewItemModel object, int id) {
          object.id = id;
        },
        objectToFB: (MedicineCourseListViewItemModel object, fb.Builder fbb) {
          final topicOffset = fbb.writeString(object.topic);
          final medicinesOffset = fbb.writeList(
              object.medicines.map(fbb.writeString).toList(growable: false));
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, topicOffset);
          fbb.addOffset(2, medicinesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MedicineCourseListViewItemModel(
              topic: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              medicines: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 8, []))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [MedicineCourseListViewItemModel] entity fields to define ObjectBox queries.
class MedicineCourseListViewItemModel_ {
  /// see [MedicineCourseListViewItemModel.id]
  static final id = QueryIntegerProperty<MedicineCourseListViewItemModel>(
      _entities[0].properties[0]);

  /// see [MedicineCourseListViewItemModel.topic]
  static final topic = QueryStringProperty<MedicineCourseListViewItemModel>(
      _entities[0].properties[1]);

  /// see [MedicineCourseListViewItemModel.medicines]
  static final medicines =
      QueryStringVectorProperty<MedicineCourseListViewItemModel>(
          _entities[0].properties[2]);
}
